# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Bailey Fluegel"
description: "Personal website of Bailey Fluegel, MIT-WHOI Ph.D. candidate in geophysics exploring Earth’s dynamic systems."
author:      "Bailey Fluegel"
